# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(username: "test_username", password: "password")

Board.create!(user_id: 1, title: "To Dos")
Board.create!(user_id: 1, title: "Life Goals")
Board.create!(user_id: 1, title: "Travel Bucket List")
Board.create!(user_id: 1, title: "Books to Read")
Board.create!(user_id: 1, title: "Media to Watch")

List.create!(board_id: 1, title: "Learn C++", ord: 1)
List.create!(board_id: 1, title: "Learn Python", ord: 2)
List.create!(board_id: 2, title: "Buy a home in San Francisco", ord: 1)
List.create!(board_id: 2, title: "Start a business", ord: 2)
List.create!(board_id: 3, title: "Europe Bucket List", ord: 1)
List.create!(board_id: 3, title: "Other Bucket List", ord: 2)
List.create!(board_id: 4, title: "Non-Fiction", ord: 1)
List.create!(board_id: 4, title: "Fiction", ord: 2)
List.create!(board_id: 5, title: "Movies", ord: 1)
List.create!(board_id: 5, title: "TV Shows", ord: 2)

Card.create!(list_id: 1, title: "Study pointers", description: "sample description", ord: 1)
Card.create!(list_id: 1, title: "Study garbage collection", description: "sample description", ord: 2)
Card.create!(list_id: 1, title: "Read The C Programming Language", description: "sample description", ord: 3)
Card.create!(list_id: 1, title: "Read The Structure and Interpretation of Computer Programs", description: "sample description", ord: 4)
Card.create!(list_id: 1, title: "Work on projects in C++", description: "sample description", ord: 5)
Card.create!(list_id: 2, title: "Learn Django", description: "sample description", ord: 1)
Card.create!(list_id: 2, title: "Learn Flask", description: "sample description", ord: 2)
Card.create!(list_id: 2, title: "Take Coursera Python course", description: "sample description", ord: 3)
Card.create!(list_id: 2, title: "Find a good Python book to read", description: "sample description", ord: 4)
Card.create!(list_id: 2, title: "Build a browser game in Python", description: "sample description", ord: 5)
Card.create!(list_id: 3, title: "Find a good-paying job", description: "sample description", ord: 1)
Card.create!(list_id: 3, title: "Save money!", description: "sample description", ord: 2)
Card.create!(list_id: 3, title: "Work harder to get a promotion", description: "sample description", ord: 3)
Card.create!(list_id: 3, title: "Find a girlfriend with a good, stable job", description: "sample description", ord: 4)
Card.create!(list_id: 3, title: "Wait forever for prices to become reasonable", description: "sample description", ord: 5)
Card.create!(list_id: 4, title: "Get 3-4 years of work experience", description: "sample description", ord: 1)
Card.create!(list_id: 4, title: "Apply to business school?", description: "sample description", ord: 2)
Card.create!(list_id: 4, title: "Apply to Y Combinator?", description: "sample description", ord: 3)
Card.create!(list_id: 4, title: "Find a talented group of friends to work with", description: "sample description", ord: 4)
Card.create!(list_id: 4, title: "Spend years thinking of a good idea", description: "sample description", ord: 5)
Card.create!(list_id: 5, title: "Croatia", description: "sample description", ord: 1)
Card.create!(list_id: 5, title: "Madrid", description: "sample description", ord: 2)
Card.create!(list_id: 5, title: "Skiing in the Alps", description: "sample description", ord: 3)
Card.create!(list_id: 5, title: "Santorini", description: "sample description", ord: 4)
Card.create!(list_id: 5, title: "Italy (especially Florence)", description: "sample description", ord: 5)
Card.create!(list_id: 6, title: "African Serengeti", description: "sample description", ord: 1)
Card.create!(list_id: 6, title: "Brazil & Argentina", description: "sample description", ord: 2)
Card.create!(list_id: 6, title: "Tibet", description: "sample description", ord: 3)
Card.create!(list_id: 6, title: "Jerusalem", description: "sample description", ord: 4)
Card.create!(list_id: 6, title: "Cairo", description: "sample description", ord: 5)
Card.create!(list_id: 7, title: "An Eternal Golden Braid", description: "sample description", ord: 1)
Card.create!(list_id: 7, title: "Nietzsche", description: "sample description", ord: 2)
Card.create!(list_id: 7, title: "Einstein Biography", description: "sample description", ord: 3)
Card.create!(list_id: 7, title: "The Economics of Life", description: "sample description", ord: 4)
Card.create!(list_id: 7, title: "Keynes Hayek", description: "sample description", ord: 5)
Card.create!(list_id: 8, title: "Murakami books", description: "sample description", ord: 1)
Card.create!(list_id: 8, title: "Nabokov books", description: "sample description", ord: 2)
Card.create!(list_id: 8, title: "100 Years of Solitude", description: "sample description", ord: 3)
Card.create!(list_id: 8, title: "The Brothers Karamazov", description: "sample description", ord: 4)
Card.create!(list_id: 8, title: "The Invisible Man", description: "sample description", ord: 5)
Card.create!(list_id: 9, title: "The Theory of Everything", description: "sample description", ord: 1)
Card.create!(list_id: 9, title: "Gone Girl", description: "sample description", ord: 2)
Card.create!(list_id: 9, title: "Straight Out of Compton", description: "sample description", ord: 3)
Card.create!(list_id: 9, title: "The Imitation Game", description: "sample description", ord: 4)
Card.create!(list_id: 9, title: "Grand Budapest Hotel", description: "sample description", ord: 5)
Card.create!(list_id: 10, title: "Game of Thrones", description: "sample description", ord: 1)
Card.create!(list_id: 10, title: "Silicon Valley", description: "sample description", ord: 2)
Card.create!(list_id: 10, title: "Suits", description: "sample description", ord: 3)
Card.create!(list_id: 10, title: "Orange Is the New Black", description: "sample description", ord: 4)
Card.create!(list_id: 10, title: "Fresh Off the Boat", description: "sample description", ord: 5)

Comment.create!(card_id: 1, user_id: 1, content: "sample content")
Comment.create!(card_id: 2, user_id: 1, content: "sample content")
Comment.create!(card_id: 3, user_id: 1, content: "sample content")
Comment.create!(card_id: 4, user_id: 1, content: "sample content")
Comment.create!(card_id: 5, user_id: 1, content: "sample content")
Comment.create!(card_id: 6, user_id: 1, content: "sample content")
Comment.create!(card_id: 7, user_id: 1, content: "sample content")
Comment.create!(card_id: 8, user_id: 1, content: "sample content")
Comment.create!(card_id: 9, user_id: 1, content: "sample content")
Comment.create!(card_id: 10, user_id: 1, content: "sample content")
Comment.create!(card_id: 11, user_id: 1, content: "sample content")
Comment.create!(card_id: 12, user_id: 1, content: "sample content")
Comment.create!(card_id: 13, user_id: 1, content: "sample content")
Comment.create!(card_id: 14, user_id: 1, content: "sample content")
Comment.create!(card_id: 15, user_id: 1, content: "sample content")
Comment.create!(card_id: 16, user_id: 1, content: "sample content")
Comment.create!(card_id: 17, user_id: 1, content: "sample content")
Comment.create!(card_id: 18, user_id: 1, content: "sample content")
Comment.create!(card_id: 19, user_id: 1, content: "sample content")
Comment.create!(card_id: 20, user_id: 1, content: "sample content")
Comment.create!(card_id: 21, user_id: 1, content: "sample content")
Comment.create!(card_id: 22, user_id: 1, content: "sample content")
Comment.create!(card_id: 23, user_id: 1, content: "sample content")
Comment.create!(card_id: 24, user_id: 1, content: "sample content")
Comment.create!(card_id: 25, user_id: 1, content: "sample content")
Comment.create!(card_id: 26, user_id: 1, content: "sample content")
Comment.create!(card_id: 27, user_id: 1, content: "sample content")
Comment.create!(card_id: 28, user_id: 1, content: "sample content")
Comment.create!(card_id: 29, user_id: 1, content: "sample content")
Comment.create!(card_id: 30, user_id: 1, content: "sample content")
Comment.create!(card_id: 31, user_id: 1, content: "sample content")
Comment.create!(card_id: 32, user_id: 1, content: "sample content")
Comment.create!(card_id: 33, user_id: 1, content: "sample content")
Comment.create!(card_id: 34, user_id: 1, content: "sample content")
Comment.create!(card_id: 35, user_id: 1, content: "sample content")
Comment.create!(card_id: 36, user_id: 1, content: "sample content")
Comment.create!(card_id: 37, user_id: 1, content: "sample content")
Comment.create!(card_id: 38, user_id: 1, content: "sample content")
Comment.create!(card_id: 39, user_id: 1, content: "sample content")
Comment.create!(card_id: 40, user_id: 1, content: "sample content")
Comment.create!(card_id: 41, user_id: 1, content: "sample content")
Comment.create!(card_id: 42, user_id: 1, content: "sample content")
Comment.create!(card_id: 43, user_id: 1, content: "sample content")
Comment.create!(card_id: 44, user_id: 1, content: "sample content")
Comment.create!(card_id: 45, user_id: 1, content: "sample content")
Comment.create!(card_id: 46, user_id: 1, content: "sample content")
Comment.create!(card_id: 47, user_id: 1, content: "sample content")
Comment.create!(card_id: 48, user_id: 1, content: "sample content")
Comment.create!(card_id: 49, user_id: 1, content: "sample content")
Comment.create!(card_id: 50, user_id: 1, content: "sample content")
